import Link from "next/link";
import CatalogueRequestDecisionForm from "@/components/CatalogueRequestDecisionForm";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";

export const dynamic = "force-dynamic";

type Request = { id: string; requested_title: string; series: string | null; volume_number: string | null; language: string | null; publisher: string | null; isbn_13: string | null; collectible_type: string; original_source_url: string | null; copyright_evidence_url: string | null; requester_notes: string; status: "pending" | "queued_for_research" | "declined" | "added_to_catalogue"; staff_notes: string | null; reviewed_by: string | null; created_at: string };

function label(value: string) { return value.replaceAll("_", " "); }

export default async function CatalogueRequestsPage() {
  const { data } = await getSupabaseAdmin().from("catalogue_requests").select("id,requested_title,series,volume_number,language,publisher,isbn_13,collectible_type,original_source_url,copyright_evidence_url,requester_notes,status,staff_notes,reviewed_by,created_at").order("created_at", { ascending: false }).limit(100);
  const requests = (data ?? []) as Request[];
  return <main className="review-page catalogue-page"><header className="site-header"><Link className="brand" href="/" aria-label="RAR Index home"><span className="brand-mark">R</span><span>RAR</span><em>Index</em></Link><Link className="header-note" href="/catalogue-import">Catalogue intake -&gt;</Link></header><section className="review-hero catalogue-hero"><div><p className="eyebrow">Community catalogue requests</p><h1>Research requests</h1><p>These are leads from collectors. They need normal source and edition review before they become RAR records.</p></div><div className="queue-total"><strong>{requests.filter((request) => request.status === "pending").length}</strong><span>awaiting review</span></div></section><section className="review-list-section"><div className="section-intro"><p className="eyebrow">Request queue</p><h2>Preserve the lead, verify the record</h2></div>{requests.length ? <div className="review-list">{requests.map((request) => <article className="review-card" key={request.id}><div className="review-card-topline"><span>{label(request.collectible_type)}</span><time>{new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(request.created_at))}</time></div><div className="review-card-main"><div><h3>{request.requested_title}</h3><p className="review-condition">{[request.series, request.volume_number, request.language, request.publisher, request.isbn_13 ? `ISBN ${request.isbn_13}` : null].filter(Boolean).join(" · ")}</p></div>{request.original_source_url ? <a className="review-source-link" href={request.original_source_url} target="_blank" rel="noreferrer">Open source ↗</a> : null}</div><div className="review-match"><p className="eyebrow">Collector note</p><p>{request.requester_notes}</p>{request.copyright_evidence_url ? <a className="review-source-link" href={request.copyright_evidence_url} target="_blank" rel="noreferrer">Open copyright proof ↗</a> : null}</div>{request.status === "pending" ? <CatalogueRequestDecisionForm requestId={request.id} /> : <div className="review-note"><span>{label(request.status)}</span><p>{request.staff_notes ?? "No staff note recorded."}{request.reviewed_by ? ` — ${request.reviewed_by}` : ""}</p></div>}</article>)}</div> : <div className="review-empty"><strong>No catalogue requests yet.</strong><p>Requests from the public edition-request page will appear here.</p></div>}</section></main>;
}
